name: "discord-action"
description: "A hard coded action that updates discord with the build status for streemtechs build pipelines."
author: deefdragon
runs:
  using: docker
  image: docker://harbor.streem.tech/streemtech-pub/discord-action:latest

inputs:
  DISCORD_BOT_TOKEN:
    description: "the token used to connect to discord by the bot"
    required: true
  DISCORD_CHANNEL:
    description: "the ID of the channel to send the message to."
    required: true
  STAGE:
    description: "What stage of the build currently being executed. Shoul be one of test,build,e2e,final-build,deploy,complete"
    required: true
  STAGE_STATUS:
    description: "The value to use to update the top level indicator"
    required: true

  DISCORD_THREAD_ID:
    description: "The id of the thread to post the message in. DISCORD_THREAD_ID and DISCORD_THREAD_MESSAGE_ID must be set tegother if set."
    required: false
    default: ""
  DISCORD_THREAD_MESSAGE_ID:
    description: "The ID of the original message that needs to be updated. DISCORD_THREAD_MESSAGE_ID and DISCORD_THREAD_ID must be set tegother if set."
    required: false
    default: ""
  STAGE_STATUS_LONG:
    description: "The longer description sent in chat for what is currently happening."
    required: false
    default: ""
  STAGE_ERROR:
    description: "The error message to print if an error occurred. Will be printed at the stage that it happened in & update the top level to be included."
    required: false
    default: ""
  PING_ROLE:
    description: "The role to ping on errors."
    required: false
    default: ""
  CANCELED_MESSAGE:
    description: "Like Error message. If set, this value will be output as a grey notice in the header, and the STAGE_STATUS_LONG will be output as a grey notice in the list of messages"
    required: false
    default: ""
