name: "Test Announcements"
on:
  workflow_dispatch:

jobs:
  github-action-go:
    runs-on: ubuntu-latest
    steps:
      - uses: streemtech/discord-action@v0
        id: initialNotice
        with:
          DISCORD_BOT_TOKEN: ${{ secrets.BUILD_BOT_TOKEN }}
          DISCORD_CHANNEL: "923504689214025728"
          SERVICE_NAME: "action"
          SERVICE_ENVIRONMENT: "PRODUCTION"
          STAGE: "test"
          STAGE_STATUS: "Init"
          DISCORD_THREAD_ID: ""
          DISCORD_THREAD_MESSAGE_ID: ""
          STAGE_STATUS_LONG: "Longer status text"
          STAGE_ERROR: ""
          PING_ROLE: "<@&988658826599342120>"

      - run: sleep 2s
        shell: bash

      - uses: streemtech/discord-action@v0
        with:
          DISCORD_BOT_TOKEN: ${{ secrets.BUILD_BOT_TOKEN }}
          DISCORD_CHANNEL: "923504689214025728"
          SERVICE_NAME: "action"
          SERVICE_ENVIRONMENT: "PRODUCTION"
          STAGE: "test"
          STAGE_STATUS: "testing"
          DISCORD_THREAD_ID: ${{ steps.initialNotice.outputs.DISCORD_THREAD_ID }}
          DISCORD_THREAD_MESSAGE_ID: ${{ steps.initialNotice.outputs.DISCORD_MESSAGE_ID }}
          STAGE_STATUS_LONG: "Running Fake Tests"
          STAGE_ERROR: ""
          PING_ROLE: "<@&988658826599342120>"

      - run: sleep 2s
        shell: bash

      - uses: streemtech/discord-action@v0
        with:
          DISCORD_BOT_TOKEN: ${{ secrets.BUILD_BOT_TOKEN }}
          DISCORD_CHANNEL: "923504689214025728"
          SERVICE_NAME: "action"
          SERVICE_ENVIRONMENT: "PRODUCTION"
          STAGE: "test"
          STAGE_STATUS: "linting"
          DISCORD_THREAD_ID: ${{ steps.initialNotice.outputs.DISCORD_THREAD_ID }}
          DISCORD_THREAD_MESSAGE_ID: ${{ steps.initialNotice.outputs.DISCORD_MESSAGE_ID }}
          STAGE_STATUS_LONG: "Running Golangci-lint"
          STAGE_ERROR: ""
          PING_ROLE: "<@&988658826599342120>"

      - run: sleep 2s
        shell: bash

      - uses: streemtech/discord-action@v0
        with:
          DISCORD_BOT_TOKEN: ${{ secrets.BUILD_BOT_TOKEN }}
          DISCORD_CHANNEL: "923504689214025728"
          SERVICE_NAME: "action"
          SERVICE_ENVIRONMENT: "PRODUCTION"
          STAGE: "test"
          STAGE_STATUS: "Cleaning"
          DISCORD_THREAD_ID: ${{ steps.initialNotice.outputs.DISCORD_THREAD_ID }}
          DISCORD_THREAD_MESSAGE_ID: ${{ steps.initialNotice.outputs.DISCORD_MESSAGE_ID }}
          STAGE_STATUS_LONG: "Lint Complete"
          STAGE_ERROR: ""
          PING_ROLE: "<@&988658826599342120>"

      - run: sleep 2s
        shell: bash

      - uses: streemtech/discord-action@v0
        with:
          DISCORD_BOT_TOKEN: ${{ secrets.BUILD_BOT_TOKEN }}
          DISCORD_CHANNEL: "923504689214025728"
          SERVICE_NAME: "action"
          SERVICE_ENVIRONMENT: "PRODUCTION"
          STAGE: "build"
          STAGE_STATUS: "Pulling Files"
          DISCORD_THREAD_ID: ${{ steps.initialNotice.outputs.DISCORD_THREAD_ID }}
          DISCORD_THREAD_MESSAGE_ID: ${{ steps.initialNotice.outputs.DISCORD_MESSAGE_ID }}
          STAGE_STATUS_LONG: "Pulling files required for build environment"
          STAGE_ERROR: ""
          PING_ROLE: "<@&988658826599342120>"

      - run: sleep 2s
        shell: bash

      - uses: streemtech/discord-action@v0
        with:
          DISCORD_BOT_TOKEN: ${{ secrets.BUILD_BOT_TOKEN }}
          DISCORD_CHANNEL: "923504689214025728"
          SERVICE_NAME: "action"
          SERVICE_ENVIRONMENT: "PRODUCTION"
          STAGE: "build"
          STAGE_STATUS: "Compiling"
          DISCORD_THREAD_ID: ${{ steps.initialNotice.outputs.DISCORD_THREAD_ID }}
          DISCORD_THREAD_MESSAGE_ID: ${{ steps.initialNotice.outputs.DISCORD_MESSAGE_ID }}
          STAGE_STATUS_LONG: "Compiling images"
          STAGE_ERROR: ""
          PING_ROLE: "<@&988658826599342120>"

      - run: sleep 2s
        shell: bash

      - uses: streemtech/discord-action@v0
        with:
          DISCORD_BOT_TOKEN: ${{ secrets.BUILD_BOT_TOKEN }}
          DISCORD_CHANNEL: "923504689214025728"
          SERVICE_NAME: "action"
          SERVICE_ENVIRONMENT: "PRODUCTION"
          STAGE: "build"
          STAGE_STATUS: "Docker Building"
          DISCORD_THREAD_ID: ${{ steps.initialNotice.outputs.DISCORD_THREAD_ID }}
          DISCORD_THREAD_MESSAGE_ID: ${{ steps.initialNotice.outputs.DISCORD_MESSAGE_ID }}
          STAGE_STATUS_LONG: "Building images in docker"
          STAGE_ERROR: ""
          PING_ROLE: "<@&988658826599342120>"

      - run: sleep 2s
        shell: bash

      - uses: streemtech/discord-action@v0
        with:
          DISCORD_BOT_TOKEN: ${{ secrets.BUILD_BOT_TOKEN }}
          DISCORD_CHANNEL: "923504689214025728"
          SERVICE_NAME: "action"
          SERVICE_ENVIRONMENT: "PRODUCTION"
          STAGE: "e2e"
          STAGE_STATUS: "Loading terraform"
          DISCORD_THREAD_ID: ${{ steps.initialNotice.outputs.DISCORD_THREAD_ID }}
          DISCORD_THREAD_MESSAGE_ID: ${{ steps.initialNotice.outputs.DISCORD_MESSAGE_ID }}
          STAGE_STATUS_LONG: "Loading terraform status stuff"
          STAGE_ERROR: ""
          PING_ROLE: "<@&988658826599342120>"

      - run: sleep 2s
        shell: bash

      - uses: streemtech/discord-action@v0
        with:
          DISCORD_BOT_TOKEN: ${{ secrets.BUILD_BOT_TOKEN }}
          DISCORD_CHANNEL: "923504689214025728"
          SERVICE_NAME: "action"
          SERVICE_ENVIRONMENT: "PRODUCTION"
          STAGE: "e2e"
          STAGE_STATUS: "starting images"
          DISCORD_THREAD_ID: ${{ steps.initialNotice.outputs.DISCORD_THREAD_ID }}
          DISCORD_THREAD_MESSAGE_ID: ${{ steps.initialNotice.outputs.DISCORD_MESSAGE_ID }}
          STAGE_STATUS_LONG: "Starting images"
          STAGE_ERROR: ""
          PING_ROLE: "<@&988658826599342120>"

      - run: sleep 2s
        shell: bash

      - uses: streemtech/discord-action@v0
        with:
          DISCORD_BOT_TOKEN: ${{ secrets.BUILD_BOT_TOKEN }}
          DISCORD_CHANNEL: "923504689214025728"
          SERVICE_NAME: "action"
          SERVICE_ENVIRONMENT: "PRODUCTION"
          STAGE: "e2e"
          STAGE_STATUS: "e2e-testing"
          DISCORD_THREAD_ID: ${{ steps.initialNotice.outputs.DISCORD_THREAD_ID }}
          DISCORD_THREAD_MESSAGE_ID: ${{ steps.initialNotice.outputs.DISCORD_MESSAGE_ID }}
          STAGE_STATUS_LONG: "Executing end to end tests"
          STAGE_ERROR: ""
          PING_ROLE: "<@&988658826599342120>"

      - run: sleep 2s
        shell: bash

      - uses: streemtech/discord-action@v0
        with:
          DISCORD_BOT_TOKEN: ${{ secrets.BUILD_BOT_TOKEN }}
          DISCORD_CHANNEL: "923504689214025728"
          SERVICE_NAME: "action"
          SERVICE_ENVIRONMENT: "PRODUCTION"
          STAGE: "e2e"
          STAGE_STATUS: "Complete"
          DISCORD_THREAD_ID: ${{ steps.initialNotice.outputs.DISCORD_THREAD_ID }}
          DISCORD_THREAD_MESSAGE_ID: ${{ steps.initialNotice.outputs.DISCORD_MESSAGE_ID }}
          STAGE_STATUS_LONG: "Tests complete. Executing cleanup."
          STAGE_ERROR: ""
          PING_ROLE: "<@&988658826599342120>"

      - run: sleep 2s
        shell: bash

      - uses: streemtech/discord-action@v0
        with:
          DISCORD_BOT_TOKEN: ${{ secrets.BUILD_BOT_TOKEN }}
          DISCORD_CHANNEL: "923504689214025728"
          SERVICE_NAME: "action"
          SERVICE_ENVIRONMENT: "PRODUCTION"
          STAGE: "deploy"
          STAGE_STATUS: "Connecting"
          DISCORD_THREAD_ID: ${{ steps.initialNotice.outputs.DISCORD_THREAD_ID }}
          DISCORD_THREAD_MESSAGE_ID: ${{ steps.initialNotice.outputs.DISCORD_MESSAGE_ID }}
          STAGE_STATUS_LONG: "Connecting to streemtech network."
          STAGE_ERROR: ""
          PING_ROLE: "<@&988658826599342120>"

      - run: sleep 2s
        shell: bash

      - uses: streemtech/discord-action@v0
        with:
          DISCORD_BOT_TOKEN: ${{ secrets.BUILD_BOT_TOKEN }}
          DISCORD_CHANNEL: "923504689214025728"
          SERVICE_NAME: "action"
          SERVICE_ENVIRONMENT: "PRODUCTION"
          STAGE: "deploy"
          STAGE_STATUS: "Update Image"
          DISCORD_THREAD_ID: ${{ steps.initialNotice.outputs.DISCORD_THREAD_ID }}
          DISCORD_THREAD_MESSAGE_ID: ${{ steps.initialNotice.outputs.DISCORD_MESSAGE_ID }}
          STAGE_STATUS_LONG: "Updating desired streemtech image"
          STAGE_ERROR: ""
          PING_ROLE: "<@&988658826599342120>"

      - run: sleep 2s
        shell: bash

      - uses: streemtech/discord-action@v0
        with:
          DISCORD_BOT_TOKEN: ${{ secrets.BUILD_BOT_TOKEN }}
          DISCORD_CHANNEL: "923504689214025728"
          SERVICE_NAME: "action"
          SERVICE_ENVIRONMENT: "PRODUCTION"
          STAGE: "deploy"
          STAGE_STATUS: "rollout"
          DISCORD_THREAD_ID: ${{ steps.initialNotice.outputs.DISCORD_THREAD_ID }}
          DISCORD_THREAD_MESSAGE_ID: ${{ steps.initialNotice.outputs.DISCORD_MESSAGE_ID }}
          STAGE_STATUS_LONG: "Rolling out new image"
          STAGE_ERROR: ""
          PING_ROLE: "<@&988658826599342120>"

      - run: sleep 2s
        shell: bash

      - uses: streemtech/discord-action@v0
        with:
          DISCORD_BOT_TOKEN: ${{ secrets.BUILD_BOT_TOKEN }}
          DISCORD_CHANNEL: "923504689214025728"
          SERVICE_NAME: "action"
          SERVICE_ENVIRONMENT: "PRODUCTION"
          STAGE: "complete"
          STAGE_STATUS: "Complete"
          DISCORD_THREAD_ID: ${{ steps.initialNotice.outputs.DISCORD_THREAD_ID }}
          DISCORD_THREAD_MESSAGE_ID: ${{ steps.initialNotice.outputs.DISCORD_MESSAGE_ID }}
          STAGE_STATUS_LONG: "Deployment Complete"
          STAGE_ERROR: ""
          PING_ROLE: "<@&988658826599342120>"

      - run: sleep 2s
        shell: bash

      - uses: streemtech/discord-action@v0
        with:
          DISCORD_BOT_TOKEN: ${{ secrets.BUILD_BOT_TOKEN }}
          DISCORD_CHANNEL: "923504689214025728"
          SERVICE_NAME: "action"
          SERVICE_ENVIRONMENT: "PRODUCTION"
          STAGE: "deploy"
          STAGE_STATUS: "Rollout Failed"
          DISCORD_THREAD_ID: ${{ steps.initialNotice.outputs.DISCORD_THREAD_ID }}
          DISCORD_THREAD_MESSAGE_ID: ${{ steps.initialNotice.outputs.DISCORD_MESSAGE_ID }}
          STAGE_STATUS_LONG: "Deployment Complete"
          STAGE_ERROR: "Rollout failure. THe step took too long"
          PING_ROLE: "<@&988658826599342120>"
