name: Version And Release
on:
  push:
    branches:
      - main
jobs:
  Patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Tag Patch
        id: tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          VERBOSE: true
          GIT_API_TAGGING: false
          DEFAULT_BUMP: patch

      - name: Parse semver string
        id: semver_parser
        uses: release-kit/semver@v2
        with:
          string: "${{ steps.tag.outputs.new_tag }}"

      - name: Tag Major
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERBOSE: true
          GIT_API_TAGGING: false
          FORCE_WITHOUT_CHANGES: true
          CUSTOM_TAG: v${{ steps.semver_parser.outputs.major }}
      - name: Tag Minor
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERBOSE: true
          GIT_API_TAGGING: false
          FORCE_WITHOUT_CHANGES: true
          CUSTOM_TAG: v${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.tag.outputs.new_tag }}
